"http://example.com/":                       # Website to check for updates
  alert     : Example.com has been updated.  # Text to display for the notification
  frequency : 60                             # Frequency (in minutes) to perform the check

"http://example.com/page/2/":                # Website to check for updates
  alert     : The second page was updated.   # Text to display for the notification
  frequency : 1440                           # Frequency (in minutes) to perform the check